[project]
name = "homelab"
version = "0.1.0"
description = "Homelab - Stan Syfert"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-terminal>=4.7.0",
    "pre-commit>=4.5.1",
]
