#cloud-config
autoinstall:
  version: 1
  locale: en_US.UTF-8
  timezone: Europe/Amsterdam
  identity:
    hostname: mbp0
    username: stan
    password: "$1$RAne92qi$dbj2HDh/Hj/VCVSHXQA2P1"
  ssh:
    install-server: true
    allow-pw: false
    authorized-keys:
    - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPKFMbjStE5sjG2Q5z3ovmbB3hTj85E4FtIC46T8NSHWDqCbMEpdN4AP2UZEjdf8tBS+LH5EGeQEQD1DTGScPodOloeU9/2OHHrjD066qIjYGa/2AWwdbnOSNxGY0sOFW//RojO8DeoK4fhWHunTbgxbzpuqFegmttyRrIkiaTQilBuIPM0Z52Dh9o1aLDnXBBScoz/txvVspNSqTgXWELO5TM3guHWaQhtHt5nEMksd0wmbtXmDu3aBXOQoQv2t1s3JIzyDk1wPLEfeiwXRM92yXv/pyV8Ww3UhdvDFol9MO00FDRQzaC6iKUQmIB2WhccSb/OgrCiG0gLnCrKGoAnDzpalTy1Ytq5zH+wVl+kfCSqTnId+9fXly5wK5LTw39P/T8VqbbQqi3s489Evh+wUOuy07NziF5fSwHzHYOP0Kz0bcKNoPb+SKIyC55HKOfsLR98JLdvEghYcDgntkQOAfTf3eYGzu2dUR3cw5JByD8lAtUZL5rJ0H+r1WEvJU= stan@tp1-ubuntu"
  storage:
    layout:
      name: direct
  packages:
    - git
    - curl
    - nano
    - python3
    - python3-pip
